BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script:
      - composer install
  cirrus_ci_macos_local_script: |
      if [ "$(uname -s)" == 'Darwin' ] && [ "$CIRRUS_CLI" == 'true' ]; then
        chmod +x vendor/bin/php-cs-fixer
        chmod +x vendor/bin/phpstan
        chmod +x vendor/bin/phpunit
        chmod +x bin/pact-stub-server/pact-stub-server
      fi
  lint_script:
      - composer run lint
  static_analysis_script:
      - composer run static-code-analysis
  generate_library_script:
      - composer gen-lib
  test_script:
      - composer test

linux_arm64_task:  
  env:
    COMPOSER_ALLOW_SUPERUSER: 1
    matrix:
      - VERSION: 8.2
      - VERSION: 8.1
      - VERSION: 8.0
  arm_container:
    dockerfile: .cirrus/linux_arm64/Dockerfile
    docker_arguments:
      VERSION: $VERSION
  version_check_script: 
      - php --version
  << : *BUILD_TEST_TASK_TEMPLATE

macos_arm64_task:
# https://www.markhesketh.com/switching-multiple-php-versions-on-macos/
  env:
    matrix:
      - VERSION: 8.2
      - VERSION: 8.1
      - VERSION: 8.0
    TART_REGISTRY_HOSTNAME: ghcr.io
    TART_REGISTRY_USERNAME: fkorotkov # GitHub supports only PATs
    TART_REGISTRY_PASSWORD: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
    AWS_ACCESS_KEY_ID: ENCRYPTED[c187b670a17eead88c1698849376273991d09678efe37ae2f0c9738c27a2422741a71c501ef4b6a4df7bff3eca5213a9]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[e456254a53b82e3167f2da23e24c389620cb3f7d47e4e5e7d993813bf9bb18c784d5cb8d88d19632073acc9e1f6096c9]
  macos_instance:
    image: ghcr.io/pact-foundation/pact-php/macos-ventura-php$VERSION-grpc:latest
  version_check_script: 
      - php --version
  << : *BUILD_TEST_TASK_TEMPLATE

build_and_publish_macos_task:
  trigger_type: manual
  env:
    matrix:
      - VERSION: 8.2
      - VERSION: 8.1
      - VERSION: 8.0
  only_if: false
  timeout_in: 3h
  update_script: brew update && brew upgrade
  info_script:
    - tart --version
    - packer --version
  build_script:
    - packer init .cirrus/macos_arm64/php-grpc.pkr.hcl
    - packer build -var php_version=$VERSION .cirrus/macos_arm64/php-grpc.pkr.hcl
  push_script:
    - tart push php$VERSION-grpc ghcr.io/pact-foundation/pact-php/macos-ventura-php$VERSION-grpc:latest
  always:
    cleanup_script:
      - tart delete php$VERSION-grpc || true
  persistent_worker:
    labels:
      name: dev-mini
