name: Triage Issue

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/triage.yml@f8fd527b1d6ff4bbf48597ef88e32772f72c644b # master
    secrets: inherit
